version: 2

models:
  - name: int_localbike__orders
    description: Orders enriched with store info (name and city)
    columns:
      - name: order_id
        description: Unique identifyer for an order
        tests:
          - not_null
          - unique
      - name: customer_id
        description: ID of the client who placed the order
      - name: store_id
        description: ID of the store from which the order was placed
        tests:
          - not_null
      - name: store_name
        description: Name of the store
      - name: store_city
        description: City of the store
      - name: order_date
        description: Date of the order
        tests:
          - not_null

  - name: int_localbike__order_items
    description: Order items enriched with products and categories infornation
    columns:
      - name: order_item_id
        description: Unique ID for an order item
        tests:
          - not_null
          - unique
      - name: order_id
        description: ID of the associated order
        tests:
          - not_null
      - name: product_id
        description: ID of a product
        tests:
          - not_null
      - name: product_name
        description: Name of the ordered product
      - name: product_price
        description: Price of one unit of the product
        tests:
          - not_null
      - name: product_quantity
        description: Quantity ordered
        tests:
          - not_null
      - name: category_id
        description: ID of the product's category
      - name: category_name
        description: Name of the product's category
      - name: total_order_item_amount
        description: Total amount for the line after discount
        tests:
          - not_null

  - name: int_localbike_sales_fact
    description: Sales fact table at order line level, enriched with customer, store, product and category information.    
    columns:
      - name: order_item_id
        description: ID for a line of order
        tests:
          - not_null
          - unique
      - name: order_id
        description: Unique ID for the associated order
        tests:
          - not_null
      - name: store_id
        description: ID for the store linked to the order
      - name: store_name
        description: Name of the store
      - name: store_city
        description: City of the store
      - name: product_id
        description: ID for the product sold
      - name: product_name
        description: Name for the product sold
      - name: category_id
        description: ID for the product category
      - name: category_name
        description: Name of teh product category
      - name: customer_id
        description: ID for the customer
      - name: order_date
        description: Date of the order
        tests:
          - not_null
      - name: product_quantity
        description: Quantity of sold products
        tests:
          - not_null
      - name: product_price
        description: Price of one unit of product
        tests:
          - not_null
      - name: total_order_item_amount
        description: Total amount for the line after discount
        tests:
          - not_null
