version: 2

models:

- name: stg_localbike__order_items
  description: "This model contains information about each item included in an order, including its price, quantity, and discount."
  columns:
    - name: order_item_id
      description: "Primary key, unique identifier for each order item."
      tests:
          - unique
          - not_null
    - name: total_order_item_amount
      description: "The total amount for this order item = (price * quantity) - (1 - discount)."
      tests:
          - not_null
      
- name: stg_localbike__orders
  description: "This model contains information about each order"
  columns:
    - name: order_id
      description: "Primary key, unique identifier for each order."
      tests:
          - unique
          - not_null

- name: stg_localbike__stores
  description: "This model lists the stores."
  columns:
    - name: store_id
      description: "Primary key, unique identifier for each store."
      tests:
          - unique
          - not_null

- name: stg_localbike__categories
  description: "This model contains information about the products categories"
  columns:
    - name: category_id
      description: "Primary key, unique identifier for each category"
      tests:
        - unique
        - not_null

- name: stg_localbike__products
  description: "This model contains details of products available for sale, primarily focusing on information about the product's brand, category, year and price."
  columns:
    - name: product_id
      description: "Primary key, unique identifier for each product."
      tests:
          - unique
          - not_null 
    - name: category_id
      description: "Foreign key linking the product to the corresponding category."
      tests:
        - relationships:
            arguments:
              name: category_id_foreign_key_in_stg_localbike__categories
              to: ref('stg_localbike__categories')
              field: category_id
        